### ISSUE TITLE
Attempting to override the the default styles of messaging center

### ISSUE THREAD

**Issue by jebzaki** [apptentive/apptentive-react-native#36]
I tried to override the messaging center styles for android using the below code.

In the android.xml
```
    <activity android:name="com.apptentive.android.sdk.ApptentiveViewActivity"
                  android:theme="@style/ApptentiveThemeOverride"/>
```

within my styles.xml
```
    <style name="ApptentiveThemeOverride">
        <item name="colorPrimary">@color/statusBlue</item>
        <item name="colorPrimaryDark">@color/statusBlue</item>
        <!-- <item name="colorBackground">#FFFFFF</item> -->
        <item name="apptentiveCardBorderColor">#757575</item>
    </style>
```

This results in the following error when I attempt to open the messaging center 
```
09-07 14:34:22.777 31374-31374/com.mmoney.wallet E/Apptentive: Exception in ApptentiveViewActivity.onCreate()
09-07 14:34:22.777 31374-31374/com.mmoney.wallet E/Apptentive: Binary XML file line #8: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
09-07 14:34:22.779 31374-31374/com.mmoney.wallet E/Apptentive: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
                                                               Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143)
                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c5 a=2}
                                                                   at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                                                                   at android.view.View.<init>(View.java:4730)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:597)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:593)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:232)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:228)
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143) 
                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-07 14:34:22.781 31374-31374/com.mmoney.wallet E/Apptentive: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143)
                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c5 a=2}
                                                                   at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                                                                   at android.view.View.<init>(View.java:4730)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:597)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:593)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:232)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:228)
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143) 
                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-07 14:34:22.781 31374-31374/com.mmoney.wallet E/Apptentive: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143)
                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c5 a=2}
                                                                   at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                                                                   at android.view.View.<init>(View.java:4730)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:597)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:593)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:232)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:228)
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143) 
                                                                   at android.app.Activity.performCreate(Activity.java:6975) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
09-07 14:34:22.782 31374-31374/com.mmoney.wallet E/Apptentive: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0100c5 a=2}
                                                                   at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:944)
                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
                                                                   at android.view.View.<init>(View.java:4730)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:597)
                                                                   at android.view.ViewGroup.<init>(ViewGroup.java:593)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:232)
                                                                   at android.support.v7.widget.Toolbar.<init>(Toolbar.java:228)
                                                                   at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                   at com.apptentive.android.sdk.ApptentiveViewActivity.onCreate(ApptentiveViewActivity.java:143)
                                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by weeeBox** [comment]
Hi @jebzaki,

Sorry for the issue. We're look at it asap.

**Comment by weeeBox** [comment]
Hey @jebzaki, sorry for the late reply. You don't need this part:
```
<activity android:name="com.apptentive.android.sdk.ApptentiveViewActivity"
	android:theme="@style/ApptentiveThemeOverride"/
```
