### ISSUE TITLE
Android: Crash when using custom person data that has a number for a value

### ISSUE THREAD

**Issue by jbolter** [apptentive/apptentive-react-native#43]
After adding custom person data to our JS code we noticed that our app was crashing on Android with this error:

```
 E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Got unknown argument class: Number
        at com.facebook.react.bridge.JavaMethodWrapper.buildArgumentExtractors(JavaMethodWrapper.java:311)
        at com.facebook.react.bridge.JavaMethodWrapper.processArguments(JavaMethodWrapper.java:236)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:346)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

According to the RN docs it seems like `Number` is not a valid argument type.  http://facebook.github.io/react-native/docs/native-modules-android.html#argument-types

I have opened a PR https://github.com/apptentive/apptentive-react-native/pull/44 to fix this issue but I'm not sure if `Integer` is appropriate or if it should be `Double` or `Float` for more precision.  I guess it depends on how this data is used on the Apptentive side of things.

**Comment by weeeBox** [comment]
@jbolter, can you provide a code snippet which led to the crash?

**Comment by jbolter** [comment]
Something like this is what is causing the crash...

`Apptentive.addCustomPersonData('Age', 28)`

**Comment by jbolter** [comment]
@weeeBox Any update on this? We are updating the SDK to get the latest critical bug fixes and are still having to use our fork until this crash is fixed for Android.

**Comment by weeeBox** [comment]
@jbolter, sorry for the delay. This was fixed in 5.3.1

**Comment by JakeRawr** [comment]
I'm experiencing the same issue with 
`Apptentive.addCustomDeviceData('coins', 543)`

**Comment by JakeRawr** [comment]
I've submitted a PR to fix this issue. https://github.com/apptentive/apptentive-react-native/pull/75
