### ISSUE TITLE
Message center returns error after app has been closed and relaunched

### ISSUE THREAD

**Issue by theAdmiralNelson** [apptentive/apptentive-react-native#51]
Hey guys, it's me again. On Android, Message Center works great if the app has just been installed. But if you close out the app and relaunch, the message center opens with "It looks like we're having trouble accessing feedback. Please wait a bit and try again."

Am I missing something?

Here are the logs:
```
2018-11-26 16:32:48.396 18392-18534/? I/Apptentive: [Apptentive Queue] [INTERACTIONS] Engage event: 'com.apptentive#app#exit'
2018-11-26 16:32:52.018 1634-2595/? I/WindowManager: WIN DEATH: Window{e12e8d2 u0 com.thekrazycouponlady.kcl/com.apptentive.android.sdk.ApptentiveViewActivity}
2018-11-26 16:33:14.659 18741-19124/? E/Apptentive: [Apptentive Queue] [CONVERSATION] Unable to add custom device data string: Apptentive SDK is not initialized.
2018-11-26 16:33:14.659 18741-19124/? E/Apptentive: [Apptentive Queue] [CONVERSATION] Unable to set person name: Apptentive SDK is not initialized.
2018-11-26 16:33:14.660 18741-19124/? E/Apptentive: [Apptentive Queue] [CONVERSATION] Unable to set person email: Apptentive SDK is not initialized.
-11-26 16:33:15.010 18741-19074/? I/Apptentive: [mqt_native_modules] Registering Apptentive Android SDK 5.3.2
2018-11-26 16:33:15.059 18741-19124/? I/Apptentive: [Apptentive Queue] [CONVERSATION] Loading 'anonymous' conversation...
2018-11-26 16:33:15.088 18741-19124/? A/Apptentive: [Apptentive Queue] Assertion failed: Not-null expected
    com.apptentive.android.sdk.debug.Assert.notNull(Assert.java:92)
    com.apptentive.android.sdk.storage.ApptentiveTaskManager.onReceiveNotification(ApptentiveTaskManager.java:310)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationObserverList.notifyObservers(ApptentiveNotificationObserverList.java:52)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationCenter.postNotification(ApptentiveNotificationCenter.java:105)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationCenter.postNotification(ApptentiveNotificationCenter.java:94)
    com.apptentive.android.sdk.conversation.ConversationManager.handleConversationStateChange(ConversationManager.java:557)
    com.apptentive.android.sdk.conversation.ConversationManager.loadActiveConversation(ConversationManager.java:183)
    com.apptentive.android.sdk.ApptentiveInternal.start(ApptentiveInternal.java:508)
    com.apptentive.android.sdk.ApptentiveInternal.access$100(ApptentiveInternal.java:78)
    com.apptentive.android.sdk.ApptentiveInternal$1.execute(ApptentiveInternal.java:238)
    com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:37)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.os.HandlerThread.run(HandlerThread.java:65)
2018-11-26 16:33:15.091 18741-19124/? A/Apptentive: [Apptentive Queue] Assertion failed: Not-null expected
    com.apptentive.android.sdk.debug.Assert.notNull(Assert.java:92)
    com.apptentive.android.sdk.storage.ApptentiveTaskManager.onReceiveNotification(ApptentiveTaskManager.java:311)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationObserverList.notifyObservers(ApptentiveNotificationObserverList.java:52)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationCenter.postNotification(ApptentiveNotificationCenter.java:105)
    com.apptentive.android.sdk.notifications.ApptentiveNotificationCenter.postNotification(ApptentiveNotificationCenter.java:94)
    com.apptentive.android.sdk.conversation.ConversationManager.handleConversationStateChange(ConversationManager.java:557)
    com.apptentive.android.sdk.conversation.ConversationManager.loadActiveConversation(ConversationManager.java:183)
    com.apptentive.android.sdk.ApptentiveInternal.start(ApptentiveInternal.java:508)
    com.apptentive.android.sdk.ApptentiveInternal.access$100(ApptentiveInternal.java:78)
    com.apptentive.android.sdk.ApptentiveInternal$1.execute(ApptentiveInternal.java:238)
    com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:37)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.os.HandlerThread.run(HandlerThread.java:65)
2018-11-26 16:33:15.092 18741-19124/? E/Apptentive: [Apptentive Queue] [CONVERSATION] Exception while fetching app configuration
2018-11-26 16:33:15.092 18741-19124/? E/Apptentive: Conversation id is null or empty
2018-11-26 16:33:15.092 18741-19124/? E/Apptentive: java.lang.IllegalArgumentException: Conversation id is null or empty
        at com.apptentive.android.sdk.comm.ApptentiveHttpClient.createAppConfigurationRequest(ApptentiveHttpClient.java:150)
        at com.apptentive.android.sdk.conversation.ConversationManager.fetchAppConfigurationGuarded(ConversationManager.java:615)
        at com.apptentive.android.sdk.conversation.ConversationManager.fetchAppConfiguration(ConversationManager.java:590)
        at com.apptentive.android.sdk.conversation.ConversationManager.handleConversationStateChange(ConversationManager.java:569)
        at com.apptentive.android.sdk.conversation.ConversationManager.loadActiveConversation(ConversationManager.java:183)
        at com.apptentive.android.sdk.ApptentiveInternal.start(ApptentiveInternal.java:508)
        at com.apptentive.android.sdk.ApptentiveInternal.access$100(ApptentiveInternal.java:78)
        at com.apptentive.android.sdk.ApptentiveInternal$1.execute(ApptentiveInternal.java:238)
        at com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:37)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2018-11-26 16:33:15.092 18741-19124/? A/Apptentive: [Apptentive Queue] Assertion failed: Missing conversation id for state: ANONYMOUS
    com.apptentive.android.sdk.conversation.ConversationManager.updateMetadataItems(ConversationManager.java:682)
    com.apptentive.android.sdk.conversation.ConversationManager.handleConversationStateChange(ConversationManager.java:580)
    com.apptentive.android.sdk.conversation.ConversationManager.loadActiveConversation(ConversationManager.java:183)
    com.apptentive.android.sdk.ApptentiveInternal.start(ApptentiveInternal.java:508)
    com.apptentive.android.sdk.ApptentiveInternal.access$100(ApptentiveInternal.java:78)
    com.apptentive.android.sdk.ApptentiveInternal$1.execute(ApptentiveInternal.java:238)
    com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:37)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.os.HandlerThread.run(HandlerThread.java:65)
2018-11-26 16:33:15.093 18741-19124/? A/Apptentive: [Apptentive Queue] Assertion failed: Not-null expected
    com.apptentive.android.sdk.debug.Assert.notNull(Assert.java:92)
    com.apptentive.android.sdk.conversation.ConversationManager.updateMetadataItems(ConversationManager.java:688)
    com.apptentive.android.sdk.conversation.ConversationManager.handleConversationStateChange(ConversationManager.java:580)
    com.apptentive.android.sdk.conversation.ConversationManager.loadActiveConversation(ConversationManager.java:183)
    com.apptentive.android.sdk.ApptentiveInternal.start(ApptentiveInternal.java:508)
    com.apptentive.android.sdk.ApptentiveInternal.access$100(ApptentiveInternal.java:78)
    com.apptentive.android.sdk.ApptentiveInternal$1.execute(ApptentiveInternal.java:238)
    com.apptentive.android.sdk.util.threading.DispatchTask.run(DispatchTask.java:37)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.os.HandlerThread.run(HandlerThread.java:65)
2018-11-26 16:33:15.102 18741-19139/? E/Apptentive: [pool-19-thread-1] [CONVERSATION] Exception while trying to update incomplete payloads
2018-11-26 16:33:15.105 18741-19139/? E/Apptentive: Conversation id is null or empty
2018-11-26 16:33:15.106 18741-19139/? E/Apptentive: java.lang.IllegalArgumentException: Conversation id is null or empty
        at com.apptentive.android.sdk.storage.ApptentiveDatabaseHelper.updateIncompletePayloads(ApptentiveDatabaseHelper.java:435)
        at com.apptentive.android.sdk.storage.ApptentiveTaskManager$11.run(ApptentiveTaskManager.java:324)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

iOS works perfectly.

**Comment by weeeBox** [comment]
Hey @theAdmiralNelson, sorry for the issue. Can you enable verbose logging and grab the logs again?

To enable verbose log level:
```
    const configuration = new ApptentiveConfiguration(
      "<APPTENTIVE_KEY>",
      "<APPTENTIVE_SIGNATURE>"
    );

    configuration.logLevel = 'verbose';
```

**Comment by weeeBox** [comment]
@theAdmiralNelson, would you be able to share logs as a plain text file? Pdf line breaks make it extremely hard to read.

**Comment by theAdmiralNelson** [comment]
For sure! Hope these are easier to read:
[Apptentive Logs.txt](https://github.com/apptentive/apptentive-react-native/files/2621383/Apptentive.Logs.txt)

**Comment by weeeBox** [comment]
@theAdmiralNelson, starting SDK 5.3.2 we forcing the legacy Android KeyStore API 18 on each new client install.
